version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2024.01

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          name: install deps
          command: sudo apt-get update && sudo apt-get install -y python3 python3-pillow

      - run:
          name: Run CI
          command: make ci

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

workflows:
  version: 2
  build:
    jobs:
      - build
